// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOGpSWjaWYDllepX-gMa-1mErqvSKW7U4',
    appId: '1:19963752533:web:b814328fae9be27ae364dc',
    messagingSenderId: '19963752533',
    projectId: 'lkfd-redpulse',
    authDomain: 'lkfd-redpulse.firebaseapp.com',
    storageBucket: 'lkfd-redpulse.firebasestorage.app',
    measurementId: 'G-VE9L1ZX2PN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAPXheOHlyB-_hLn23PgyeVKU449mEpWU',
    appId: '1:19963752533:android:d523de44685caa2ce364dc',
    messagingSenderId: '19963752533',
    projectId: 'lkfd-redpulse',
    storageBucket: 'lkfd-redpulse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNE7db7NNJm-2FAW0-8WNYOOq2Ixn4IME',
    appId: '1:19963752533:ios:d93d7ce18170be3ee364dc',
    messagingSenderId: '19963752533',
    projectId: 'lkfd-redpulse',
    storageBucket: 'lkfd-redpulse.firebasestorage.app',
    iosBundleId: 'com.example.redpulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNE7db7NNJm-2FAW0-8WNYOOq2Ixn4IME',
    appId: '1:19963752533:ios:d93d7ce18170be3ee364dc',
    messagingSenderId: '19963752533',
    projectId: 'lkfd-redpulse',
    storageBucket: 'lkfd-redpulse.firebasestorage.app',
    iosBundleId: 'com.example.redpulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOGpSWjaWYDllepX-gMa-1mErqvSKW7U4',
    appId: '1:19963752533:web:97b6770ed0db7140e364dc',
    messagingSenderId: '19963752533',
    projectId: 'lkfd-redpulse',
    authDomain: 'lkfd-redpulse.firebaseapp.com',
    storageBucket: 'lkfd-redpulse.firebasestorage.app',
    measurementId: 'G-B4GB6Y2BWJ',
  );
}
